---
- name: Prepare
  hosts: all
  pre_tasks:
    - include_role:
        name: asymworks.baseline
        tasks_from: pre-tasks.yaml

    # Override the Alpine Diskless Mode fact since the docker container will
    # not show a mount point for '/'
    - when: ansible_facts['os_family']|lower == 'alpine'
      set_fact:
        alpine_diskless: false

  roles:
    - asymworks.baseline

  post_tasks:
    - include_role:
        name: asymworks.baseline
        tasks_from: post-tasks.yaml

  vars:
    asset_name: molecule-container
    asset_tag: c:molecule:01
