---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 5"

defaults:
  run:
    working-directory: asymworks.docker

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: asymworks.docker

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install ansible ansible-lint

      - name: Lint code
        run: |
          set -e
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: alpine:3.14
            command: /sbin/init

          - image: alpine:3.15
            command: /sbin/init

          - image: alpine:3.16
            command: /sbin/init

          - image: debian:10
            command: /lib/systemd/systemd

          - image: debian:11
            command: /lib/systemd/systemd

          - image: ubuntu:20.04
            command: /lib/systemd/systemd

          - image: ubuntu:22.04
            command: /lib/systemd/systemd

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: asymworks.docker

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install ansible ansible-lint "molecule[docker,lint]<4.0"

      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker

      - name: Test code
        run: molecule test -s ci
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          CI_DOCKER_IMAGE: ${{ matrix.image }}
          CI_DOCKER_COMMAND: ${{ matrix.command }}
          MOLECULE_NO_LOG: 'false'
